version: 2.1


jobs:
  build-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: sudo docker build . -t danielgran/debian-base:manifest-arm64v8 --build-arg ARCH=arm64v8
      - run: docker push danielgran/debian-base:manifest-arm64v8

  build-amd64:
    machine:
      image: ubuntu-2004:current
     resource_class: medium
     steps:
      - checkout
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: sudo docker build . -t danielgran/debian-base:manifest-amd64 --build-arg ARCH=amd64
      - run: docker push danielgran/debian-base:manifest-amd64

   manifest:
     machine:
       image: ubuntu-2004:current
     resource_class: medium
     steps:
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: docker manifest create \
        danielgran/debian-base:manifest-latest \
        --amend danielgran/debian-base:manifest-arm64v8 \
        --amend danielgran/debian-base:manifest-amd64
      - run: docker manifest push danielgran/debian-base:manifest-latest
       
       


workflows:
  build-and-publish:
    jobs:
      - build-arm64
      - build-amd64
      - manifest

