version: 2.1


jobs:
  build-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: apt update && apt upgrade -y
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: docker build -t danielgran/debian-base:latest .
      - run: docker push danielgran/debian-base:latest


workflows:
  build-and-publish:
    jobs:
      - build-arm64
