version: 2.1

jobs:
  build-linux:
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64/v8
    steps:
      - checkout
      - run:
          name: Log in to docker hub
          command: |
            docker login -u danielgran -p $DOCKERHUBKEY
      - run:
          name: Build and push from dockerfile
          command: |
            docker buildx create --use
            docker buildx build --push --tag danielgran/debian-base:latest --platform $BUILDX_PLATFORMS .

  build-macos:
    macos:
      xcode: 15.4.0
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64/v8
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            brew install --cask docker
            open /Applications/Docker.app
            sleep 60  # Wait for Docker to start
      - run:
          name: Log in to docker hub
          command: |
            docker login -u danielgran -p $DOCKERHUBKEY
      - run:
          name: Build and push from dockerfile
          command: |
            docker buildx create --use
            docker buildx build --push --tag danielgran/debian-base:latest --platform $BUILDX_PLATFORMS .

  build-windows:
    machine:
      image: windows-server-2022-gui:current
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64/v8
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            choco install docker-desktop
            Start-Process 'C:\Program Files\Docker\Docker\Docker Desktop.exe'
            Start-Sleep -Seconds 60  # Wait for Docker to start
      - run:
          name: Log in to docker hub
          command: |
            docker login -u danielgran -p $DOCKERHUBKEY
      - run:
          name: Build and push from dockerfile
          command: |
            docker buildx create --use
            docker buildx build --push --tag danielgran/debian-base:latest --platform $BUILDX_PLATFORMS .

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-linux
      - build-macos
      - build-windows