version: 2.1


jobs:
  build-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: sudo docker build . -t danielgran/debian-base:manifest-arm64v8 --build-arg ARCH=arm64v8
      - run: docker push danielgran/debian-base:manifest-arm64v8
      - run: docker manifest create danielgran/debian-base:latest --amend danielgran/debian-base:manifest-arm64v8


workflows:
  build-and-publish:
    jobs:
      - build-arm64
