version: 2.1


jobs:
  build-and-push-arm64v8:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: docker buildx build --push --platform linux/arm64/v8 --build-arg ARCH=arm64v8 --tag danielgran/debian-base:latest-arm64v8 .
  build-and-push-amd64:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: docker buildx build --push --platform linux/amd64 --build-arg ARCH=amd64 --tag danielgran/debian-base:latest-amd64 .

  build-and-push-macos126:
    macos:
      xcode: 14.2.0
    steps:
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: docker buildx build --push --tag danielgran/debian-base:latest-macos126 .


workflows:
  build-and-publish:
    jobs:
      - build-and-push-arm64v8
      - build-and-push-amd64
      - build-and-push-macos126
