version: 2.1


jobs:
  build-and-push:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: docker login -u danielgran -p $DOCKERHUBKEY
      - run: docker buildx build |
        --push
        --platform linux/arm64/v8,linux/amd64
        --tag danielgran/debian-base

workflows:
  build-and-publish:
    jobs:
      - build-and-push

