version: 2.1


jobs:
  build-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: docker login -u danielgran -p $DOCKERHUBKEY


workflows:
  build-and-publish:
    jobs:
      - build-arm64
