name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        username: danielgran
        password: ${{ secrets.DOCKERHUBKEY }}
    - name: Build
      run: docker build . -t danielgran/debian-base:latest
    - name: Push
      run: docker push danielgran/debian-base:latest
